package com.waypoint.core.domain.model

import kotlinx.datetime.Instant
import kotlinx.serialization.Serializable

/**
 * The root domain type — a complete travel plan generated by the AI.
 *
 * `id` is generated client-side at the moment we finalise streaming.
 * `createdAt` is captured at the same moment, in UTC.
 *
 * The whole tree (Itinerary → Day → Activity) is immutable. New versions
 * are produced by `copy(...)` from the streaming parser and the ViewModel
 * reducer; nothing in the domain mutates in place.
 */
@Serializable
data class Itinerary(
    val id: String,
    val title: String,
    val destination: String,
    val days: List<Day>,
    val createdAt: Instant,
)

@Serializable
data class Day(val dayNumber: Int, val summary: String, val activities: List<Activity>)

@Serializable
data class Activity(
    /** "HH:mm" — kept as string because the model emits it as text and the UI displays it as text. */
    val time: String,
    val title: String,
    val description: String,
    val locationName: String,
    val lat: Double?,
    val lng: Double?,
) {
    /** True when we have enough info to drop a map pin. */
    val hasCoordinates: Boolean get() = lat != null && lng != null
}
